export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_INGREDIENTS_ERROR = 'SET_INGREDIENTS_ERROR';

export const SET_ORDERS = 'SET_ORDERS';
export const SET_ORDERS_ERROR = 'SET_ORDERS_ERROR';
export const SET_LOADING = 'SET_LOADING';
export const PLACE_ORDER = 'PLACE_ORDER';
export const PLACE_ORDER_ERROR = 'PLACE_ORDER_ERROR';